/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visual;

import javax.swing.JLabel;

/**
 *
 * @author Xavier Siguachi
 */
public class Informacion extends javax.swing.JPanel {

    /**
     * Creates new form Informacion
     */
    public Informacion() {
        initComponents();
    }

    public JLabel getLabelCodigo() {
        return labelCodigo;
    }

    public JLabel getLabelNombre() {
        return labelNombre;
    }

    public JLabel getLabelSuscrito() {
        return labelSuscrito;
    }

    public JLabel getLabelTemperatura() {
        return labelTemperatura;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelSuscrito = new javax.swing.JLabel();
        labelTemperatura = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 3, 14)); // NOI18N
        jLabel1.setText("Nombre: ");
        add(jLabel1);
        jLabel1.setBounds(30, 50, 80, 18);

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 3, 14)); // NOI18N
        jLabel2.setText("Código:");
        add(jLabel2);
        jLabel2.setBounds(30, 20, 60, 20);

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 3, 14)); // NOI18N
        jLabel3.setText("Suscrito:");
        add(jLabel3);
        jLabel3.setBounds(30, 80, 80, 20);

        labelCodigo.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        labelCodigo.setText("jLabel4");
        add(labelCodigo);
        labelCodigo.setBounds(90, 20, 110, 20);

        labelNombre.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        labelNombre.setText("jLabel5");
        add(labelNombre);
        labelNombre.setBounds(90, 50, 100, 20);

        labelSuscrito.setFont(new java.awt.Font("JetBrains Mono", 2, 14)); // NOI18N
        labelSuscrito.setText("jLabel6");
        add(labelSuscrito);
        labelSuscrito.setBounds(110, 80, 100, 20);

        labelTemperatura.setFont(new java.awt.Font("Lato Medium", 0, 18)); // NOI18N
        labelTemperatura.setText("Temperatura");
        add(labelTemperatura);
        labelTemperatura.setBounds(180, 50, 450, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSuscrito;
    private javax.swing.JLabel labelTemperatura;
    // End of variables declaration//GEN-END:variables
}
